authorization-server: http://localhost:5000

server:
  port: 5001
security:
  oauth2:
    sso:
      login-path: /sso
    client:
      access-token-uri: ${authorization-server}/auth/oauth/token
      user-authorization-uri: ${authorization-server}/auth/oauth/authorize
      client-id: 301575942
      client-secret: wangyiyunyinyue
    resource:
      token-info-uri: ${authorization-server}/auth/oauth/check_token